services:
  - type: web
    name: buy-ya
    env: node
    rootDir: api
    buildCommand: npm install && cd ../admin && npm install --include=dev && npm run build
    startCommand: npm start
    plan: starter
    autoDeploy: true