services:
  - type: web
    name: buy-ya-api
    runtime: node
    region: oregon
    buildCommand: npm install --prefix api
    startCommand: npm run start --prefix api
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
