services:
  - type: web
    name: buy-ya-api
    runtime: node
    region: oregon
    buildCommand: npm install --prefix api && npm install --prefix admin && npm run build --prefix admin
    startCommand: npm run start --prefix api && npm run start --prefix admin
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
